# Искусственный Интеллект
## Рабочая тетрадь № 2
### Хречко Сергей Викторович ИКБО-03-21

## 1.1 Теоретический материал – Типы данных
NumPy (NumericalPython) - это библиотека Python с открытым исходным кодом, которая используется практически во всех областях науки и техники. Это универсальный стандарт для работы с числовыми данными в Python.

Если у вас уже есть Python, вы можете установить NumPy с помощью командной строки:

     pip install numpy

Чтобы начать использовать NumPy необходимо импортировать соответствующую библиотеку:

    import numpy as np

Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа. Наиболее важные атрибуты объектов ndarray:

- ndarray.ndim - число измерений (чаще их называют "оси") массива.
- ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
- ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
- ndarray.dtype - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. NumPy здесь предоставляет целый букет возможностей, как встроенных, например: bool_, character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, object_, так и возможность определить собственные типы данных, в том числе и составные.
- ndarray.itemsize - размер каждого элемента массива в байтах.
- ndarray.data - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.

Подробнее о массивах в NumPy можно найти в официальной документации https://numpy.org/doc/stable/user/absolute_beginners.html


### 1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, значение элемента с индексом (3,1) и второй столбец. Индексация начинается с нуля.

In [1]:
import numpy as np
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


### 1.2.2 Пример
Задача:
Пример. Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный нулями.
2. Создать вектор размера 10, заполненный единицами.
3. Создать вектор размера 10, заполненный заданным числом.
4. Создать вектор со значениями от 10 до 19.


In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


### 1.2.3 Пример
Задача:
Создать массив 10x10 со случайными значениями, найти минимум, максимум и среднее значение

In [3]:
Z = np.random.random((10, 10))
Zmin, Zmax, Zmean = Z.min(), Z.max(), Z.mean()
print(Zmin, Zmax, Zmean)

0.004084511701596405 0.9873326695454044 0.5329878290317296


### 1.2.4 Пример
Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице местами

In [7]:
a = np.arange(25).reshape(5, 5)
a[[0, 1]] = a[[1, 0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### 1.2.5 Пример
Задача:
Выяснить результат следующих выражений:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

In [8]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### 1.2.6 Пример
Задача:
Отсортировать массив.

In [9]:
arr = np.array([2, 4, 1, 5, 3])
print(np.sort(arr))

[1 2 3 4 5]


### 1.3.1 Задание
Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.


In [21]:
a = np.full(64, 0).reshape(8, 8)
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


### 1.3.2 Задание
Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.


In [22]:
a = np.arange(5)
a = np.tile(a, (5, 1))
#tile - повторение массива, в данном случае повторение массива
#  a 5 раз по вертикали и 1 раз по горизонтали
print(a)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 1.3.3 Задание
Задача:
Создать массив 3x3x3 со случайными значениями

In [23]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.2265139  0.12343256 0.70458504]
  [0.39133854 0.39159875 0.21597432]
  [0.0206116  0.49334832 0.99298187]]

 [[0.79850243 0.71579469 0.13050039]
  [0.89002958 0.30047895 0.80118553]
  [0.33884486 0.6113863  0.63162268]]

 [[0.48768273 0.90789327 0.97437402]
  [0.1707832  0.7013375  0.58038597]
  [0.86728319 0.07259065 0.15887267]]]


### 1.3.4 Задание
Задача:
Создать матрицу с 0 внутри, и 1 на границах.

In [24]:
a = np.full(64, 1).reshape(8, 8)
a[1:len(a) - 1, 1:len(a) - 1] = 0
print(a)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


### 1.3.5 Задание
Задача:
Создайте массив и отсортируйте его по убыванию

In [26]:
a = np.array([2, 3, 5, 1, 4])
a = np.sort(a)[::-1]
print(a)

[5 4 3 2 1]


### 1.3.6 Задание
Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [28]:
a = np.arange(64).reshape(8, 8)
print(a.shape)
print(a.ndim)
print(a.size)

(8, 8)
2
64


## 2.1 Теоретический материал – Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения является введение исходных данных в систему. Исходные данные могут вводиться вручную, содержаться в файле или храниться в интернете в какомлибо формате. Кроме того, часто требуется получить данные из нескольких источников.

Библиотека pandas – это удобный и быстрый инструмент для работы с данными, обладающий большим функционалом. Если очень кратко, то pandas – это библиотека, которая предоставляет очень удобные с точки зрения использования инструменты для хранения данных и работе с ними.

Библиотека pandas присутствует в стандартной поставке Anaconda. Если же ее там нет, то его можно установить отдельно. Для этого введите командной строке:

 pip install pandas

Для импорта библиотеки используйте команду:

import pandas as pd

Библиотека pandas предоставляет две ключевые структуры данных:

Series и DataFrame.
- Series – это одномерная структура данных, ее можно представить, как таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда можно использовать ключ для доступа к элементам данных.
- DataFrame – это двумерная структура. Идейно она очень похожа на обычную таблицу, что выражается в способе ее создания и работе с ее элементами.

### 2.2.1 Пример
Задача:
Создать Series из списка Python, словаря Python, и массива Numpy (установить буквенные метки для последнего).

In [31]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
ndarr = np.array([1, 2, 3, 4, 5])


s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


### 2.2.2 Пример
Задача:
Дано два Series. Напечатать их первые элементы и все элементы после
третьего (во втором фрейме).

In [32]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


### 2.2.3 Пример
Задача:
Создайте новый фрейм данных.

In [33]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Иван', 'Петр', 'Сидор']
dataframe['Возраст'] = [20, 21, 19]
dataframe['Водитель'] = [True, False, False]
dataframe

Имя  Возраст  Водитель
0   Иван       20      True
1   Петр       21     False
2  Сидор       19     False